### PR TITLE
use 32px icons for navigation buttons

### PR DESCRIPTION
**Pull request by diversys**
Fixes blurry navigation icons

### CODE REVIEW

**Comment by extrowerk** [comment]
Thanks! Good Job!

**Comment by diversys** [comment]
Hmm, this commit somehow breaks favicon and search button appearance

screen shot 2017-07-27 at 01 09 37

**Comment by extrowerk** [comment]
@diversys : it looks ok to me, but maybe i don't notice something...

**Comment by diversys** [comment]
Also selection border seems to be 64px which is too large compared to Web+...

**Comment by diversys** [comment]
Before the commit:

screen shot 2017-07-27 at 08 28 33

**Comment by extrowerk** [comment]
@diversys : it seems the bigger the icon is, the bigger will be the selection border too and it brakes the favicon.

**Pull request merged**
